[2025-03-17T01:22:38.829+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-03-17T01:22:37.303253+00:00 [queued]>
[2025-03-17T01:22:38.839+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-03-17T01:22:37.303253+00:00 [queued]>
[2025-03-17T01:22:38.841+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-17T01:22:38.858+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2025-03-17 01:22:37.303253+00:00
[2025-03-17T01:22:38.862+0000] {standard_task_runner.py:57} INFO - Started process 51 to run task
[2025-03-17T01:22:38.868+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2025-03-17T01:22:37.303253+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpgdt99_qv']
[2025-03-17T01:22:38.869+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask reddit_extraction
[2025-03-17T01:22:38.911+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-03-17T01:22:37.303253+00:00 [running]> on host bfa63cabed93
[2025-03-17T01:22:38.955+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vijay Mopuru' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T01:22:37.303253+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-17T01:22:37.303253+00:00'
[2025-03-17T01:22:39.167+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_dag.py", line 20, in reddit_pipeline
    for submission in subreddit_obj.top(time_filter=time_filter, limit=int(limit)):
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 66, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 90, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 731, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 514, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 46, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 963, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 234, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 186, in _make_request
    response = self._rate_limiter.call(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/rate_limit.py", line 46, in call
    kwargs["headers"] = set_header_callback()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 378, in refresh
    self._request_token(grant_type="client_credentials", **additional_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url=url, **data)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 59, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response
[2025-03-17T01:22:39.181+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20250317T012237, start_date=20250317T012238, end_date=20250317T012239
[2025-03-17T01:22:39.192+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task reddit_extraction (received 401 HTTP response; 51)
[2025-03-17T01:22:39.220+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-17T01:22:39.234+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
